In [1]:
import numpy as np

In [39]:
from typing import List, NamedTuple

In [3]:
from collections import Counter

In [4]:
a = ['ali', 'jafar', 'naghi', 'ali', 'henry', 'doolborideh', 'coco', 'ali', 'ali']

In [5]:
a_dict = {}
for elem in a:
    if elem in a_dict.keys():
        a_dict[elem] += 1
    else:
        a_dict[elem] = 1

In [6]:
a_dict

{'ali': 4, 'jafar': 1, 'naghi': 1, 'henry': 1, 'doolborideh': 1, 'coco': 1}

In [8]:
ca = Counter(a)

In [18]:
a,b = ca.most_common(1)[0]

('ali', 4)

In [19]:
def raw_majority_vote(labels: List[str]) -> str:
    votes = Counter(labels)
    winner = votes.most_common(1)[0][0]
    return winner

In [23]:
assert raw_majority_vote(a) == 'ali'

In [24]:
b = [1,10, 15, 20, 135,123234]

list comprehension 

In [32]:
[num * 2 for num in b]

[2, 20, 30, 40, 270, 246468]

In [31]:
c = []
for num in b:
    c.append(num * 2)
c

[2, 20, 30, 40, 270, 246468]

In [37]:
def majority_vote(labels: List[str]) -> str:
    """ 
    
    """
    vote_counts = Counter(labels)
    winner, winner_count = vote_counts.most_common(1)[0]
    num_winners = len(
    [count for count in vote_counts.values() if count == winner_count]    
    )
    if num_winners == 1 :
        return winner
    else:
        return majority_vote(labels[:-1])

In [38]:
assert majority_vote(['a', 'b', 'c', 'b', 'a']) == 'b'


In [43]:
x = [1,2,3]

In [48]:
y = [1,1,1]

In [45]:
x2 = np.array(x)

In [46]:
x2

array([1, 2, 3])

Broadcasting 

In [47]:
x2 * 2 

array([2, 4, 6])

In [50]:
y2 = np.array(y)

In [51]:
x2 - y2 

array([0, 1, 2])

In [52]:
np.power(x2,2)

array([1, 4, 9])

In [53]:
def dist(x,y):
    x = np.array(x)
    y = np.array(y)
    dist = np.sqrt(np.sum(np.power(x - y, 2)))
    return dist 

In [58]:
b = [10,1, 6,2,5]

In [60]:
b

[1, 2, 5, 6, 10]

In [71]:
b[:3]

[1, 2, 5]

In [62]:
sorted(b)

[1, 2, 5, 6, 10]

In [72]:
def knn_classify(k, labeled_points, labeled_y, new_point):
#     all_distances = [dist(point, new_point) for point in labeled_point]
#     all_distances.sort()
#     dists = all_distances[:k]
#     labels = labeled_y[:k]
    # Order the labeled points from nearest to farthest.
    by_distance = sorted(labeled_points,
                         key=lambda lp: distance(lp.point, new_point))

    # Find the labels for the k closest
    k_nearest_labels = [lp.label for lp in by_distance[:k]]
    # and let them vote.
    return majority_vote(k_nearest_labels)

In [73]:
import random 

In [76]:
def random_point(dim: int):

    return [random.random() for _ in range(dim)]

In [80]:
import mglearn

In [81]:
from sklearn.model_selection import train_test_split 

In [82]:
X,y = mglearn.datasets.make_forge()

/Users/ala/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:85: DeprecationWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=DeprecationWarning)


In [86]:
x_train, x_test, y_train, y_test = train_test_split(X, y)

In [92]:
from sklearn.neighbors import KNeighborsClassifier

In [130]:
knn = KNeighborsClassifier(n_neighbors=3)

In [124]:
knn.fit(x_train, y_train )

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [125]:
knn.predict(x_test)

array([1, 1, 0, 1, 1, 0, 1])

In [126]:
y_test 

array([1, 1, 0, 0, 1, 1, 1])

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [128]:
confusion_matrix(y_test, knn.predict(x_test))

array([[1, 1],
       [1, 4]])

In [129]:
accuracy_score(y_test, knn.predict(x_test))

0.7142857142857143