In [1]:
import numpy as np 

In [12]:
class Person():
    def __init__(self, name, age, height):
        self.name = name 
        self.age = age 
        self.height = height 
    def say_my_name(self):
        print('Yo, my name is {}'.format(self.name))

In [13]:
Ala = Person('Ala', 34, 175)

In [14]:
Ala.name

'Ala'

In [15]:
Ala.say_my_name()

Yo, my name is Ala


In [16]:
Lisa = Person('Lisa', 35, 189)

In [17]:
Lisa.name

'Lisa'

In [18]:
Lisa.say_my_name()

Yo, my name is Lisa


In [63]:
class LogisticRegression():
    def __init__(self, lr=0.001, n_iter=500):
        self.lr = lr 
        self.n_iter = n_iter
        self.weights = None
        self.bias = None 
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def fit(self, x, y):
        n_samples, n_features = x.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        for _ in range(self.n_iter):
            linear_model = self.bias + np.dot(x, self.weights) 
            y_pred = self.sigmoid(linear_model)
            
            dw = (1/n_samples) * np.dot(x.T, (y_pred - y))
            db = (1/n_samples) * np.sum(y_pred - y)
            
            self.weights = self.weights - self.lr * dw 
            self.bias = self.bias - self.bias * db
    
    def predict(self, x_test):
        linear_model = self.bias + np.dot(x_test, self.weights) 
        y_pred = self.sigmoid(linear_model)
        y_pred_cls = [1 if i > 0.5 else 0 for i in y_pred]
        return y_pred_cls
        
        
            
                

In [21]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

In [22]:
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [23]:
bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [49]:
regressor = LogisticRegression(lr=0.0001, n_iter=1000)
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)

In [50]:
regressor.weights

array([ 3.15293049e-02,  4.38654849e-02,  1.82410610e-01,  7.27537516e-02,
        2.81717878e-04, -1.58894498e-04, -5.94872879e-04, -2.47273428e-04,
        5.52004467e-04,  2.26787536e-04,  1.51094736e-04,  3.05656080e-03,
       -1.13192918e-03, -8.17035574e-02,  1.44511066e-05, -4.65302767e-05,
       -7.39516318e-05, -1.01056532e-05,  5.54792013e-05,  1.84699735e-06,
        3.33667572e-02,  5.58231396e-02,  1.82917393e-01, -9.88324945e-02,
        3.48801253e-04, -6.74346105e-04, -1.27431569e-03, -2.94185000e-04,
        7.76940692e-04,  1.96640459e-04])

In [51]:
regressor.bias

0.0

In [35]:
X_train.shape

(455, 30)

In [52]:
y_pred = regressor.predict(X_test)

In [54]:
accuracy(y_pred, y_test)

0.9298245614035088

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
confusion_matrix(y_pred, y_test)

array([[39,  2],
       [ 6, 67]])

In [60]:
from sklearn.linear_model import LogisticRegression as LR

In [61]:
model = LR()

In [64]:
LogisticRegression

__main__.LogisticRegression

In [65]:
LR

sklearn.linear_model.logistic.LogisticRegression

In [66]:
model.fit(X_train, y_train)

/Users/ala/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
y2 = model.predict(X_test)

In [68]:
y2

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0])

In [70]:
accuracy(y2, y_test)

0.9473684210526315